.*Assembler messages:
.*:4: Error: offset \(\+1048576\) is invalid for J-type immediate
.*:5: Error: offset \(-1048578\) is invalid for J-type immediate
.*:8: Error: offset \(\+1048576\) is invalid for J-type immediate
.*:10: Error: offset \(-1048578\) is invalid for J-type immediate
.*:14: Error: offset \(\+1048576\) is invalid for J-type immediate
.*:17: Error: offset \(-1048578\) is invalid for J-type immediate
.*:20: Error: offset \(\+1\) is invalid for CJ-type immediate
