.*Assembler messages:
.*:8: Error: offset \(\+2147481600\) too large for PC-relative offset
.*:11: Error: offset \(-2147485697\) too large for PC-relative offset
.*:17: Error: offset \(\+2147481600\) too large for PC-relative offset
.*:21: Error: offset \(-2147485697\) too large for PC-relative offset
.*:26: Error: offset \(\+2147481600\) too large for PC-relative offset
.*:30: Error: offset \(-2147485697\) too large for PC-relative offset
