.*: Assembler messages:
.*: Error: illegal operands `amocas\.q a1,a4,\(a3\)'
.*: Error: illegal operands `amocas\.q a0,a5,\(a3\)'
.*: Error: illegal operands `amocas\.q\.aq a1,a4,\(a3\)'
.*: Error: illegal operands `amocas\.q\.aq a0,a5,\(a3\)'
.*: Error: illegal operands `amocas\.q\.rl a1,a4,\(a3\)'
.*: Error: illegal operands `amocas\.q\.rl a0,a5,\(a3\)'
.*: Error: illegal operands `amocas\.q\.aqrl a1,a4,\(a3\)'
.*: Error: illegal operands `amocas\.q\.aqrl a0,a5,\(a3\)'
