.*: Assembler messages:
.*: Error: illegal operands `amocas\.d a1,a4,\(a3\)'
.*: Error: illegal operands `amocas\.d a0,a5,\(a3\)'
.*: Error: illegal operands `amocas\.d\.aq a1,a4,\(a3\)'
.*: Error: illegal operands `amocas\.d\.aq a0,a5,\(a3\)'
.*: Error: illegal operands `amocas\.d\.rl a1,a4,\(a3\)'
.*: Error: illegal operands `amocas\.d\.rl a0,a5,\(a3\)'
.*: Error: illegal operands `amocas\.d\.aqrl a1,a4,\(a3\)'
.*: Error: illegal operands `amocas\.d\.aqrl a0,a5,\(a3\)'
