.*: Assembler messages:
.*: Error: unrecognized opcode `fcvt\.d\.h fa0,fa1', extension `zfhmin' and `d', or `zhinxmin' and `zdinx' required
.*: Error: unrecognized opcode `fcvt\.d\.h fa0,fa1', extension `d' required
.*: Error: unrecognized opcode `fcvt\.d\.h fa0,fa1', extension `zfhmin' required
.*: Error: unrecognized opcode `fcvt\.d\.h a0,a1', extension `zdinx' required
.*: Error: unrecognized opcode `fcvt\.d\.h a0,a1', extension `zhinxmin' required
