.*: Assembler messages:
.*: Error: unrecognized opcode `prefetch\.i \(x1\)', extension `zicbop' required
.*: Error: unrecognized opcode `prefetch\.i 0x20\(x1\)', extension `zicbop' required
.*: Error: unrecognized opcode `prefetch\.r \(x16\)', extension `zicbop' required
.*: Error: unrecognized opcode `prefetch\.r -2048\(x16\)', extension `zicbop' required
.*: Error: unrecognized opcode `prefetch\.w \(x31\)', extension `zicbop' required
.*: Error: unrecognized opcode `prefetch\.w \+0x7e0\(x31\)', extension `zicbop' required
